apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dauzct7r7-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-be62445545.x8xz.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:7e29daa277fadc9418cff5938ea5ad25cb20e5f2@sha256:6c7881bf80d8a4a657380cf57170faa13b3cb0d25229b8a25c68074b8a7a496b
          name: container-image
